# Generated by Django 5.1.2 on 2025-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeafPost', '0003_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
