# Generated by Django 5.1.2 on 2025-05-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LeafPost', '0004_remove_post_categories_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=600)),
                ('message', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
